### ISSUE TITLE
css-validator Fails on Empty File

### ISSUE THREAD

**Issue by niedzielski** [twolfson/css-validator#6]
On css-validator v0.7.0, `css-validator /dev/null` or `touch empty.css && css-validator empty.css` fail with:

```
node_modules/css-validator/lib/cli.js:99
      throw err;
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

When I use the web UI, it prints an error as well (both with file upload and direct input):

```
CSS
Validator
Error
Target: No file

I/O Error: You have sent an invalid request.
```

I think the library can and should work with an empty file but I'm not sure if you agree or how you would wish to implement a workaround.

**Comment by twolfson** [comment]
I think I would expect no validation errors as well. I don't have time to
take care of this any time soon. Can you open a PR and add a test case?
